name: GitHub Actions
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  linter:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50
        env:
          CGO_ENABLED: 0
  tests:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Run tests
        run: go test -cover ./...
        env:
          CGO_ENABLED: 0
